language: node_js
node_js:
  - "node"
  - "6"
  - "8"
  - "10"

dist: trusty
sudo: required

addons:
  sonarqube:
    organization: "bluet-github"
    token:
      secure: "XBVsW2e/cX2yc4Raxd+quWth54Ya3HVfXgYBUcmd2zbscmk/6un7uoeoiKB6wzdxAAy9MZCLOzQ+MdFpScaoXPDUrRq/MHayjwTxk5Ezz1IixbYIhv78PbeyyMcse8GjqwkXAn6EthHX7TPsbKhcS3EXZhvDheFgPbiTE0mGjH8Lp6MWYGbQ1d87J1b24LdqPzCrfQKmurok/7LHe0fJH6+Xw6oCjNQYuPiW+wZA4ta6U28k8CgSGvz9Cygsg8lMfRJoP4H3b6ahjxsnCFfmzJlBeTy6cnvxr/dGgINw4rRbWH2+Mq10IDXILZfEahrhT3EqRoa+U7HBDGKSd8j2zOLYmDIurbvK0Vl5WxssZEmn2vtvPZ8jPq8MxyDlFEZfAShIWBYwPSGMH3EbTxVT7+xdAD9CXMv25VZ8j2f6zD5B8v8FWR78uSQKaRjL4ZyUt3cgBPeKwCoDriTLu0GUprxEzALEX+cErWkDV+PlFvX5Rof61ZF8JSUKDEVtHkekeNNilzreQzhbpbSqI/LimZKm9RPzv4VeETx5IhvMhDXJ4u8IHtcm2QUw/LLdzrNGDC0UUO9hSKDPB1ytF8WiW5ZcADpsKx+CQ/SJKsXDJ7wjE30dyOy+NvqLwGYGoyl1MaTBFtQMUg46lDtuimCEV895w+wUChQVPW7adUQaBW0="
jdk:
  - oraclejdk8
script:
  - npm test
  - sonar-scanner
cache:
  directories:
    - '$HOME/.sonar/cache'
